export const cards = [
    "angular2",
    "vue",
    "react",
    "grunt",
    "phantomjs",
    "ember",
    "babel",
    "ionic",
    "gulp",
    "meteor",
    "yeoman",
    "yarn",
    "nodejs",
    "bower",
    "browserify",
  ];